server:
    port: 8081


spring:
    application:
        name: user-service

    datasource:
        url: ${PG_DATABASE_URL:jdbc:postgresql://localhost:5432/budget-buddy-users}
        username: ${PG_DATABASE_USERNAME:postgres}
        password: ${PG_DATABASE_PASSWORD:password}

    output:
        ansi:
            enabled: ALWAYS

    jpa:
        hibernate:
            ddl-auto: update


eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://host.docker.internal:8761/eureka}

    
    instance:
        leaseRenewalIntervalInSeconds: 30
