server:
    port: 8081


spring:
    application:
        name: user-service

    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/budget-buddy-users}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:password}

    output:
        ansi:
            enabled: ALWAYS

    jpa:
        hibernate:
            ddl-auto: update


eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

    
    instance:
        leaseRenewalIntervalInSeconds: 30


# creating the rabbitmq fanout exchange
exchanges:
    fanout: delete-user                         # name of the exchange

# creating the routing key for the exchange
routing-key: key1234